import { gql } from 'apollo-angular';

export const LOGIN = gql`
  query Login($email: String!, $password: String!) {
    loginUsingEmail(email: $email, password: $password) {
      userId
      email
      token
      registration_token
      tokenExpiration
      designation
      role
      message
    }
  }
`;

export const USERDATA = gql`
query UserData($user_id: String!){
    GetUser(user_id: $user_id)
    {
      id
      first_name
      middle_name
      last_name
      username
      email
      designation
      phone_number_for_login
      registration_token
       user_is_active
      joined_date
      preferred_communication
      farmcount
      heatcount24hours
      illnesscount24hours
      beltsassigned24hours
      animalcount
      active_heat_alerts_count
      active_illness_count
      pregnant_animals_count
      recoverylistcount
      createdAt
      updatedAt
      
      sub_user{
        id
        first_name
        middle_name
        last_name
        username
        designation
        email

        section_location_id{

          section_location_id
          location_name
          current_capacity
          capacity
          location_details
          status
          description
          address
          rating
          organisationID
          serviceProfileID
          serviceProfileName
          animalcount
          heatcount24hours
          illnesscount24hours
          beltsassigned24hours
          active_heat_alerts_count
          active_illness_count
          pregnancy_awaited_count
          pregnant_animals_count
          createdAt
          updatedAt
        }
      }

      section_location_id{

        section_location_id
        location_name
        current_capacity
        capacity
        location_details
        status
        description
        address
        rating
        organisationID
        serviceProfileID
        serviceProfileName
        animalcount
        heatcount24hours
        illnesscount24hours
        beltsassigned24hours
        active_heat_alerts_count
        active_illness_count
        pregnancy_awaited_count
        pregnant_animals_count
        createdAt
        updatedAt

        owner{
          id
          first_name
          middle_name
          last_name
          username
          designation
          email

          section_location_id{

            section_location_id
            location_name
            current_capacity
            capacity
            location_details
            status
            description
            address
            rating
            organisationID
            serviceProfileID
            serviceProfileName
            animalcount
            heatcount24hours
            illnesscount24hours
            beltsassigned24hours
            active_heat_alerts_count
            active_illness_count
            pregnancy_awaited_count
            pregnant_animals_count
            createdAt
            updatedAt
          }

        }

        users{
          id
          first_name
          middle_name
          last_name
          username
          designation
          email

          section_location_id{

            section_location_id
            location_name
            current_capacity
            capacity
            location_details
            status
            description
            address
            rating
            organisationID
            serviceProfileID
            serviceProfileName
            animalcount
            heatcount24hours
            illnesscount24hours
            beltsassigned24hours
            active_heat_alerts_count
            active_illness_count
            pregnancy_awaited_count
            pregnant_animals_count
            createdAt
            updatedAt
          }
        }

        heatalert24hours{
          id
          cattle_id
          device_id
          prediction_of_heat_timestamp
          heatStrength
          predicted_Insemination_timedate_start
          predicted_Insemination_timedate_end
          vet_checkup_if_cow_is_in_heat
          active
        }

        illnessalert24hours{
                   id
                   cattle_id
                   device_id
                   current_status
                   treatment_type
                   type_of_illness
                   treatment_given_timestamp
                   treatment_started
                   healthIndex
                   home_remedy{
                     id
                     illness
                     status
                     medicine_name
                     changes_in_nutrition
                     createdAt
                     updatedAt
                   }
                   reason_for_no_action
                   type_of_action
                   medicine
                   nutrition
                   other_details
                   createdAt
                   updatedAt
         }

         installations{
          device_id
          cattle_id
          name
          deviceStatusBattery
          deviceStatusBatteryLevel
          assigned
        }

        inseminations{
          id
          device_id
          cattle_id
          insemination_date
          insemination_time
          type_of_insemination
          process_of_insemination
          semen_origin
          heat_alert{
            id
            cattle_id
            device_id
          }
        }

        animals{
          id
          farm
          {
            section_location_id
            location_name
            status
            createdAt
            updatedAt
          }
          belt{
            device_id
            cattle_id
            name
            applicationID
            description
            deviceProfileID
            deviceProfileName
            assigned
            createdAt
            updatedAt
          }
          source_of_entry
          date_of_entry
          type
          breed
          name
          date_of_birth
          image_link
          category{
            id
            cattle_id
            gender
            age
            pregnancy_status
            milking_status
            createdAt
            updatedAt
          }
          weight
          average_food
          average_milk
          injured
          injured_remarks
          is_active
          reason_of_exit
          date_of_exit
           milking{
            id
            cattle_id
            date
            morning
            afternoon
            evening
            createdAt
            updatedAt
          }
          heat_alert{
            id
            cattle_id
            device_id
            prediction_of_heat_timestamp
            heatStrength
            predicted_Insemination_timedate_start
            predicted_Insemination_timedate_end
            vet_checkup_if_cow_is_in_heat
            active
            createdAt
            updatedAt
          }
          inseminations{
            id
            device_id
            cattle_id
            insemination_date
            insemination_time
            type_of_insemination
            process_of_insemination
            semen_origin
            heat_alert{
              id
              cattle_id
              device_id
            }
          }
          lactation_cycle{
            id
            breed
            device_id
            cattle_id
            insemination_date
            insemination_time
            process_of_insemination
            type_of_insemination
            dry_date_start{
              predicted
              actual
            }
            dry_date_end{
              predicted
              actual
            }
            calf_delivery{
              id
              lactation_cycle
              predicted_date_start
              predicted_date_end
              actual_date_of_delivery
              delivery_number
              calf_gender
              createdAt
              updatedAt
            }
            vaccination{
              id
              lactation_cycle
              list_of_vaccines
              {
                id
                title_name
                due_date
                vaccination_number
                date_of_vaccination
                remarks
                createdAt
                updatedAt
              }
              createdAt
              updatedAt
            }
            semen_origin
            createdAt
            updatedAt
          }
          illness{
            id
            cattle_id
            device_id
            current_status
            treatment_type
            type_of_illness
            treatment_given_timestamp
            treatment_started
            healthIndex
            home_remedy{
              id
              illness
              status
              medicine_name
              changes_in_nutrition
              createdAt
              updatedAt
            }
            reason_for_no_action
            type_of_action
            medicine
            nutrition
            other_details
            createdAt
            updatedAt
          }

          illness_recovery_list{
            id
            cattle_id
            device_id
            current_status
            treatment_type
            type_of_illness
            treatment_given_timestamp
            treatment_started
            healthIndex
          }

          heatcount24hours
          illnesscount24hours
          recoverylistcount
          active_heat_alerts{
            id
            cattle_id
            device_id
            prediction_of_heat_timestamp
            heatStrength
            predicted_Insemination_timedate_start
            predicted_Insemination_timedate_end
            vet_checkup_if_cow_is_in_heat
            active
            createdAt
            updatedAt
          }
          active_illness{
            id
            cattle_id
            device_id
            current_status
            treatment_type
            type_of_illness
            treatment_given_timestamp
            treatment_started
            healthIndex
            createdAt
            updatedAt
          }
          illness_recovery_list{
            id
            cattle_id
            device_id
            current_status
            treatment_type
            type_of_illness
            treatment_given_timestamp
            treatment_started
            healthIndex
            createdAt
            updatedAt
          }
          pregnant_animals{
            id
            cattle_id
            pregnancy_status
            createdAt
            updatedAt
          }
          pregnancy_awaited{
            id
            cattle_id
            pregnancy_status
            createdAt
            updatedAt
          }
          createdAt
          updatedAt

        }
      }

      heatalert24hours{
        id
        cattle_id
        device_id
        prediction_of_heat_timestamp
        heatStrength
        predicted_Insemination_timedate_start
        predicted_Insemination_timedate_end
        vet_checkup_if_cow_is_in_heat
        active
      }

      illnessalert24hours{
       id
                cattle_id
                device_id
                current_status
                treatment_type
                type_of_illness
                treatment_given_timestamp
                treatment_started
                healthIndex
                home_remedy{
                  id
                  illness
                  status
                  medicine_name
                  changes_in_nutrition
                  createdAt
                  updatedAt
                }
                reason_for_no_action
                type_of_action
                medicine
                nutrition
                other_details
                createdAt
                updatedAt
      }

      inseminations{
        id
        device_id
        cattle_id
        insemination_date
        insemination_time
        type_of_insemination
        process_of_insemination
        semen_origin
        heat_alert{
          id
          cattle_id
          device_id
        }
      }
      installations{
        device_id
        cattle_id
        name
        deviceStatusBattery
        deviceStatusBatteryLevel
        assigned
      }

    }
}
`
